name: X

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      run: |
        echo "MI_VARIABLE_SECRETA=${{ secrets.prueba }}"
        echo $mivariable
        if [[ "${{ secrets.prueba }}" == "hola" ]]; then
          echo "verdadero"
        else
          echo "falso"
        fi


    env:
      mivariable: ${{secrets.prueba}}  
